export const prefix = "activity/";

export const MutationTypes = {
  SET_GLOBAL_SNAPSHOTS: "SET_GLOBAL_SNAPSHOTS",
  SET_SNAPSHOTS: "SET_SNAPSHOTS",
  SET_SNAPSHOTS_LOADED: "SET_SNAPSHOTS_LOADED",
  SET_TRANSACTIONS: "SET_TRANSACTIONS",
  SET_SNAPSHOTS_END: "SET_SNAPSHOTS_END",
  SET_GLOBAL_SNAPSHOTS_END: "SET_GLOBAL_SNAPSHOTS_END",
  REMOVE_GLOBAL_SNAPSHOTS: "REMOVE_GLOBAL_SNAPSHOTS"
} as const;

export const ActionTypes = {
  LOAD_GLOBAL_SNAPSHOTS: "LOAD_GLOBAL_SNAPSHOTS",
  LOAD_SNAPSHOTS: "LOAD_SNAPSHOTS",
  LOAD_TRANSACTIONS: "LOAD_TRANSACTIONS"
} as const;
