export const prefix = "page/";

export const MutationTypes = {
  UPDATE_SEND_CONTACTS: "UPDATE_SEND_CONTACTS",
  REMOVE_SEND_CONTACTS: "REMOVE_SEND_CONTACTS",
  SET_SNAPSHOT_DETAIL: "SET_SNAPSHOT_DETAIL",
  RESET_PAGE_STATE: "RESET_PAGE_STATE"
} as const;
