export const prefix = "wallet/";

export const GetterTypes = {
  GET_ASSET_BY_ID: "GET_ASSET_BY_ID",
  GET_MERGED_ASSETS: "GET_MERGED_ASSETS",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  TOTAL_BTC: "TOTAL_BTC",
  TOTAL_USD: "TOTAL_USD"
} as const;

export const MutationTypes = {
  ADD_ADDITION_ASSET: "ADD_ADDITION_ASSET",
  REMVOE_ADDITION_ASSET: "REMVOE_ADDITION_ASSET",
  SET_ASSETS: "SET_ASSETS",
  SET_ASSET: "SET_ASSET",
  SET_EXCHANGE_RATES: "SET_EXCHANGE_RATES",
  SET_ME: "SET_ME",
  SET_USERS: "SET_USERS",
  RESET_WALLET: "RESET_WALLET",
  SET_AUTH_ERROR: "SET_AUTH_ERROR"
} as const;

export const ActionTypes = {
  LOAD_ASSET: "LOAD_ASSET",
  LOAD_ASSETS: "LOAD_ASSETS",
  LOAD_EXCHANGE_RATES: "LOAD_EXCHANGE_RATES",
  LOAD_ME: "LOAD_ME",
  LOAD_USER: "LOAD_USER"
} as const;
