name: Push Main
on:
  push:
    branches:
      - main

jobs:
  master:
    strategy:
      matrix:
        step: ["build:release"]
    name: ${{ matrix.step }}
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]') && github.repository == 'fox-one/fennec'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: actions/setup-node@v2
        with:
          node-version: "12.14.1"
          cache: "yarn"

      - name: ${{ matrix.step }}
        env:
          GH_PAT: ${{  secrets.GH_PAT }}
          GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_RELEASE_FILES: ${{ secrets.GH_RELEASE_FILES }}
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn ${{ matrix.step }}

  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: |
          echo "Dummy skip step"
